# ansible-playbook test_ctakes.yml --user=gms --ask-sudo-pass
---
- hosts: 127.0.0.1
  connection: local
  #sudo: true
  vars:
    ctakes_dir: ../ctakes
    ctakes_url: http://mirror.stjschools.org/public/apache//ctakes/ctakes-4.0.0/apache-ctakes-4.0.0-bin.tar.gz   
    user: gms
  tasks:
  - name: Prepare Install folder
    file: path={{ctakes_dir}} state=directory
    become: yes
    become_user: gms
  - name: Extract Ctakes
    unarchive: src={{ctakes_url}}
               dest={{ctakes_dir}}
               remote_src=true
