apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-mm-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  volumes:
  - name: test-rtf
    hostPath: # change this accordingly to your host system
      path: /home/gms/projects/k8s/cpc
  
  templates:

  - name: nlp-adapt-metamap-services
    steps:
    - - name: metamap-server-annotator
        template: run-metamap
        withSequence: # spin up arbitrary number pods
          count: 1

    - - name: mmannotator-deployment
        template: mmannotator-d
    - - name: mmannotator-service
        template: mmannotator-s
    - - name: mmserver-deployment
        template: mmserver-d
    - - name: mmserver-service
        template: mmserver-s


  # mmannotator deployment/service
  - name: mmannotator-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mmannotator
        spec:
          selector:
            matchLabels:
              app: mmannotator
              track: stable
          template:
            metadata:
              labels:
                app: mmannotator
                track: stable
            spec:
                #nodeSelector:
                #node: atlas0
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/mmannotator
                imagePullPolicy: Never
                command: ["/usr/share/public_mm/src/uima/bin/deployMetamapPipeline.sh"] 
                name: mmannotator
                ports:
                - containerPort: 31166
                livenessProbe:
                  exec:
                    command:
                    - /bin/sh
                    - -c
                    - nslookup mmserver.default && 
                      nslookup mmannotator.default
                  initialDelaySeconds: 30
                env:
                - name: MMSERVER_HOST 
                  value: mmserver.default
                - name: MMSERVER_PORT
                  value: "8066"

  
  - name: mmannotator-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mmannotator
          namespace: default
          labels:
            app: mmannotator
        spec:
          selector:
            app: mmannotator
          ports:
          - port: 31166
            targetPort: 31166

       
  - name: mmserver-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mmserver
        spec:
          selector:
            matchLabels:
              app: mmserver
              track: stable
          template:
            metadata:
              labels:
                app: mmserver
                track: stable
            spec:
                #nodeSelector:
                #node: atlas0
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/mmserver
                imagePullPolicy: Never
                command: ["mmserver"] 
                name: mmserver
                ports:
                - containerPort: 8066
                livenessProbe:
                  exec:
                    command:
                    - /bin/sh
                    - -c
                    - nslookup mmannotator.default && 
                      nslookup mmserver.default && 
                      nslookup wsd.default && 
                      nslookup medpost.default
                  initialDelaySeconds: 60
                env:
                - name: TAGGER_SERVER_HOSTS 
                  value: medpost.default
                - name: WSD_SERVER_HOSTS
                  value: wsd.default

  - name: mmserver-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mmserver
          namespace: default
          labels:
            app: mmserver
        spec:
          selector:
            app: mmserver
          ports:
          - port: 8066
            targetPort: 8066

