apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-mm-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  volumes:
  - name: test-rtf
    hostPath: # change this accordingly to your host system
      path: /home/gms/projects/k8s/cpc
  
  templates:

  - name: nlp-adapt-clamp
    steps:
    - - name: clamp
        template: run-clamp
        withSequence: # spin up arbitrary number pods
          count: 1

  - name: run-clamp
    daemon: true
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/clamp
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/biomedicus/bin/deployClampPipeline.sh"] 
      env:
      - name: _JAVA_OPTIONS
        value: "-Dhttp.proxyHost=HOSTNAME -Dhttp.proxyPort=3128 -Dhttps.proxyHost=HOSTNAME -Dhttps.proxyPort=3128"
      - name: umls_user          
        value: "USERNAME"
      - name: umls_pass          
        value: "PASSWORD"
      stdin: true
      tty: true
      name: clamp

  - name: run-client-clamp
    nodeSelector:
      node: thalia2
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/cpc
      imagePullPolicy: Never
      env:
        - name: NLPADAPT_BROKER_URI
          value: nio://amq.default:61616
        - name: NLPADAPT_DATASOURCE_URI #NLPADAPT_DATASOURCE_URI
          value: jdbc:oracle:thin:@ctsidbprod0.ahc.umn.edu:1521:TIDEPRDP
        #- name: NLPADAPT_DATASOURCE_USERNAME
        #  value: NLP_ADAPT[NLP_SANDBOX]
        #- name: NLPADAPT_DATASOURCE_PASSWORD
        #  value: aifa0iepah_m1Iex
        - name: NLPADAPT_DATASOURCE_USERNAME
          value: <USER NAME>
        - name: NLPADAPT_DATASOURCE_PASSWORD
          value: <PW>
      command: ["/bin/bash","-c", "groovy /home/groovy/scripts/clamp_client.groovy"]
      volumeMounts:
      - name: test-rtf
        mountPath:  /home/groovy/data
        readOnly: false
