# ansible-playbook test_ctakes.yml --user=gms --ask-sudo-pass
---
- hosts: 127.0.0.1
  connection: local
  #sudo: true
  vars:
    download_dir: ../
    es_dir: ../elasticsearch-2.1.0
    es_url: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.1.0.tar.gz    
    es_src: elasticsearch-2.1.0.tar.gz
    user: gms
  tasks:
  - name: Prepare Install folder
    file: path={{es_dir}} state=directory
    become: yes
    become_user: gms
  - name: Extract ElasticSearch
    unarchive: src={{es_url}}
               dest={{es_dir}}
               remote_src=true
