# ansible-playbook test_ctakes.yml --user=gms --ask-sudo-pass
---
- hosts: 127.0.0.1
  connection: local
  #sudo: true
  vars:
    nlptab_dir: ../nlptab-webapp
    nlptab_url: https://github.com/nlpie/nlptab-webapp.git
    user: gms
  tasks:
  - git:
      repo: "{{nlptab_url}}"
      dest: "{{nlptab_dir}}"
      clone: yes
      update: yes

