apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  
  templates:

  - name: nlp-adapt-metamap-services
    steps:
    - - name: mmannotator-deployment
        template: mmannotator-d
    - - name: mmannotator-service
        template: mmannotator-s
    - - name: mmserver-deployment
        template: mmserver-d
    - - name: mmserver-service
        template: mmserver-s
    - - name: rtf-deployment
        template: rtf-d
    - - name: rtf-service
        template: rtf-s


#  - name:  mmannotator-daemon
#    daemon: true
#    container:
#      image: ahc-nlpie-docker.artifactory.umn.edu/mmannotator
#      imagePullPolicy: Never
#      command: ["/usr/share/public_mm/src/uima/bin/deployMetamapPipeline.sh"] 
#      stdin: true 
#      tty: true 
#    metadata:
#      labels:
#        app: mmannotator

  # mmannotator deployment/service
  - name: mmannotator-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mmannotator
        spec:
          selector:
            matchLabels:
              app: mmannotator
              track: stable
          template:
            metadata:
              labels:
                app: mmannotator
                track: stable
            spec:
                #dns: dns1
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/mmannotator
                imagePullPolicy: Never
                command: ["/usr/share/public_mm/src/uima/bin/deployMetamapPipeline.sh"] 
                name: mmannotator
                ports:
                - containerPort: 31166

  
  - name: mmannotator-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mmannotator
          namespace: default
          labels:
            app: mmannotator
        spec:
          selector:
            app: mmannotator
          ports:
          - port: 31166
            targetPort: 31166

       
  - name: mmserver-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mmserver
        spec:
          selector:
            matchLabels:
              app: mmserver
              track: stable
          template:
            metadata:
              labels:
                app: mmserver
                track: stable
            spec:
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/mmserver
                imagePullPolicy: Never
                name: mmserver
                ports:
                - containerPort: 8066
                env:
                - name: TAGGER_SERVER_HOSTS 
                  value: medpost.default
                - name: WSD_SERVER_HOSTS
                  value: wsd.default

  - name: mmserver-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mmserver
          namespace: default
          labels:
            app: mmserver
        spec:
          selector:
            app: mmserver
          ports:
          - port: 8066
            targetPort: 8066

  - name: rtf-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: rtf
        spec:
          selector:
            matchLabels:
              app: rtf
              track: stable
          template:
            metadata:
              labels:
                app: rtf
                track: stable
            spec:
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/biomedicus
                imagePullPolicy: Never
                command: ["/usr/share/biomedicus/bin/deployRtfPipeline.sh"] 
                name: rtf
                ports:
                - containerPort: 35555

  - name: rtf-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: rtf
          namespace: default
          labels:
            app: rtf
        spec:
          selector:
            app: rtf
          ports:
          - port: 35555
            targetPort: 35555

