apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  
  templates:

  - name: nlp-adapt-metamap-services
    steps:
    - - name: medpost-deployment
        template: medpost-server-d
    - - name: medpost-service
        template: medpost-server-s
    - - name: wsd-deployment
        template: wsd-server-d
    - - name: wsd-service
        template: wsd-server-s
  
  - name: medpost-server-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: medpost
        spec:
          selector:
            matchLabels:
              app: medpost
              track: stable
          template:
            metadata:
              labels:
                app: medpost
                track: stable
            spec:
              nodeSelector:
                node: bpb
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/medpost
                imagePullPolicy: Never
                command: ["wsd_foreground start"] 
                resources:
                  limits:
                    memory: "1G"
                  requests:
                    memory: "500M"
                name: medpost
                ports:
                - containerPort: 1795

  - name: medpost-server-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: medpost
          namespace: default
          labels:
            app: medpost
        spec:
          selector:
            app: medpost
          ports:
          - port: 1795
            targetPort: 1795

       
  - name: wsd-server-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: wsd
        spec:
          selector:
            matchLabels:
              app: wsd
              track: stable
          template:
            metadata:
              labels:
                app: wsd
                track: stable
          
            spec:
              nodeSelector:
                node: hermes
              containers:
              - image: ahc-nlpie-docker.artifactory.umn.edu/wsd
                imagePullPolicy: Never
                command["skrmedpost_foreground start"]
                resources:
                  limits:
                    memory: "3G"
                  requests:
                    memory: "500M"
                name: wsd
                ports:
                - containerPort: 5554

  - name: wsd-server-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: wsd
          namespace: default
          labels:
            app: wsd
        spec:
          selector:
            app: wsd
          ports:
          - port: 5554
            targetPort: 5554

       
