apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  
  templates:

  - name: nlp-adapt-metamap-services
    steps:
    - - name: mmannotator-daemon
        template: mmannotator-daemon
    - - name: mmannotator-service
        template: mmannotator-s

  - name:  mmannotator-daemon
    daemon: true
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/mmannotator
      imagePullPolicy: Never
      command: ["/usr/share/public_mm/src/uima/bin/deployMetamapPipeline.sh"] 
      stdin: true 
      tty: true 
    metadata:
      labels:
        app: mmannotator

  
  - name: mmannotator-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mmannotator
          namespace: default
          labels:
            app: mmannotator
        spec:
          selector:
            app: mmannotator
          ports:
          - port: 31166
            targetPort: 31166



       
