apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt-metamap-services          #invoke the build template
  volumes:
  - name: test-rtf
    hostPath: # change this accordingly to your host system
      path: /home/gms/projects/k8s/cpc
  
  templates:

  - name: nlp-adapt-metamap-services
    steps:
    - - name: client
        template: run-client

  - name: run-client
    nodeSelector:
      node: atlas0
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/cpc
      imagePullPolicy: Never
      resources:
        limits:
          memory: "10G"
        requests:
          memory: "500M"
      env:
        - name: NLPADAPT_BROKER_URI
          value: nio://amq.default:61616
        - name: NLPADAPT_INPUT_DATASOURCE_URI #NLPADAPT_DATASOURCE_URI
          value: jdbc:sqlite:mimic-rtf.db
      command: ["/bin/bash","-c", "groovy /home/groovy/scripts/client.groovy"]
      volumeMounts:
      - name: test-rtf
        mountPath:  /home/groovy/data
        readOnly: false

