apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt          #invoke the build template
  volumes:
  - name: test-volume
    hostPath:
      path: /Users/gregsilverman/workspace/test # must match host directory in minikube; cannot be symlinked
      # path: /Volumes/GrenziData/development/data
  
  templates:

  - name: nlp-adapt
    steps:
    - - name: biomedicus
        template: run-biomedicus

    - - name: metamap 
        template: run-metamap

    - - name: ctakes 
        template: run-ctakes

    - - name: clamp 
        template: run-clamp
  
  - name: run-biomedicus
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/biomedicus
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/biomedicus/scripts/run_biomedicus.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-metamap
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/metamap
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/public_mm/scripts/run_metamap.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-ctakes
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/ctakes
      imagePullPolicy: Never
      tty: true
      stdin: true
      env:
        - name: ctakes_umlspw          
          value: "UMLS PW HERE"
        - name: ctakes_umlsuser          
          value: "UMLS USER HERE"
      command: ["/usr/share/ctakes/scripts/run_ctakes.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-clamp
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/clamp
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/clamp/scripts/run_clamp.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
      - name: clamp-configmap
          mountPath: /user/share/clamp/CLAMP.LICENSE

  - name: run-amicus
    container:
      image: ahc-nlpie-docker.artifactory.umn.edu/amicus
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/public_mm/scripts/run_amicus.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
