FROM openjdk:8-jre

ADD biomedicus-distribution-2.2.0-SNAPSHOT-release /usr/share/biomedicus

COPY required/biomedicus-as  /usr/share/biomedicus

#RUN chmod 755 /usr/share/biomedicus/scripts/run_biomedicus.sh

